"""Creating users table

Revision ID: f7dabd420a13
Revises: 
Create Date: 2023-02-16 23:07:50.474621

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f7dabd420a13"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("role", sa.String(), server_default="user", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)

    # ### Inserting records into `users` table
    op.execute(
        """
        -- password = 123456
        INSERT INTO users (id, name, email, password)
        VALUES 
            (-5, 'samar','smr@user.com','$2b$12$QTNq8kikPjrnJ.oAGffqBeFaPsMxTAQ7kZwL4G5oLll4yCQ7ZDgIa'),
            (-4, 'sabry','sbr@user.com','$2b$12$A10IXrRUDNO.DuzMTS899OO0oTgHk04AoPqUZSVPNdnsJJeN6w8sC'),
            (-3, 'gad','gad@user.com','$2b$12$qsgVC6ks35SJ4wnZiCcnWepNXAj5nq.QoCVQAOyHxzkjbPyZN784C'),
            (-2, 'shabrway','shbr@user.com','$2b$12$TrxmcyzYkfHgPQ9DHpBce.uBQh61Lf53nyUqP2E4dCeyLK57CrU1q'),
            (-1, 'moatasem','m@admin.com','$2b$12$bC4K2BirQ1nXdk3T/xQFcOM2qxsZ3zPUyhz5uED.lxVZiOt7Gjine')
        """
    )

    # resetting the auto incremental
    op.execute("ALTER SEQUENCE users_id_seq RESTART WITH 1")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
